'use client';
import { useMemo,useState } from 'react';
import { Activity,ArrowRight,Atom,BookOpen,CheckCircle2,ChevronRight,CircleGauge,ExternalLink,Gauge,Menu,Orbit,Ruler,Waves,X,Zap } from 'lucide-react';
import { Button } from '@/components/ui/button';

const years=[
 {year:'1ª série',title:'Movimento e energia',focus:'Medir → representar → prever',missions:['Movimento: do vídeo ao gráfico','Forças e interações','Energia, trabalho e potência','Gravitação e órbitas'],bncc:'EM13CNT101 · 204 · 205'},
 {year:'2ª série',title:'Ondas e campos',focus:'Perturbar → detectar → comunicar',missions:['Oscilações e ondas','Som e audição','Luz, óptica e imagens','Eletricidade e circuitos'],bncc:'EM13CNT103 · 301 · 308'},
 {year:'3ª série',title:'Fronteiras da Física',focus:'Modelar → argumentar → decidir',missions:['Magnetismo e indução','Termodinâmica e clima','Quântica e matéria','Relatividade, cosmos e tecnologia'],bncc:'EM13CNT102 · 106 · 209 · 302'}];
const labs=[
 {icon:Ruler,title:'Analisador de movimento',question:'Como a inclinação de x(t) revela a velocidade?',method:'Vídeo, quadro a quadro, tabela e gráfico',evidence:'Gráfico anotado + incerteza',risk:'Digital'},
 {icon:Waves,title:'Bancada de ondas',question:'O que muda ao variar frequência e tensão?',method:'Pulso, régua, cronômetro e repetição',evidence:'Relação v = λf apoiada em dados',risk:'Digital / corda'},
 {icon:Zap,title:'Circuitos sob teste',question:'A corrente é consumida pelos componentes?',method:'Medições em série e paralelo',evidence:'Modelo de carga e energia',risk:'Baixa tensão'},
 {icon:Orbit,title:'Órbitas e gravitação',question:'Por que cair pode significar permanecer em órbita?',method:'Simulação e comparação de modelos',evidence:'Previsão + diagrama de forças',risk:'Digital'}];
const media=[
 {org:'MEC',title:'BNCC — Ciências da Natureza',kind:'Documento curricular',href:'https://www.gov.br/mec/pt-br/cne/bncc_ensino_medio.pdf'},
 {org:'PhET • Univ. Colorado',title:'Forças e Movimento',kind:'Simulação em português',href:'https://phet.colorado.edu/sims/html/forces-and-motion-basics/latest/forces-and-motion-basics_pt_BR.html'},
 {org:'PhET • Univ. Colorado',title:'Onda em uma Corda',kind:'Laboratório digital',href:'https://phet.colorado.edu/sims/html/wave-on-a-string/latest/wave-on-a-string_pt_BR.html'},
 {org:'NASA Science',title:'Journey to the Stars',kind:'Filme educativo • 6º–12º+',href:'https://science.nasa.gov/learn/heat/resource/journey-to-the-stars-planetarium-show/'},
 {org:'CERN',title:'CERN for Students',kind:'Vídeos e visitas virtuais',href:'https://home.cern/resources?audience=36'},
 {org:'NASA',title:'NASA STEM — Students',kind:'Vídeos, desafios e projetos',href:'https://www.nasa.gov/learning-resources/for-students-grades-9-12/'}];

export function PhysicsStudio(){const[force,setForce]=useState(24),[mass,setMass]=useState(6),[year,setYear]=useState(0),[menu,setMenu]=useState(false);const a=useMemo(()=>force/mass,[force,mass]);return <main className="relative min-h-screen overflow-hidden">
 <header className="glass sticky top-0 z-50 border-b px-5 py-3 lg:px-10"><div className="mx-auto flex max-w-[1500px] items-center justify-between"><a href="#inicio" className="flex items-center gap-3 font-bold"><span className="grid size-10 place-items-center rounded-full border-2 border-primary text-primary"><Atom/></span><span>Einstein <em className="not-italic text-primary">/ laboratório</em></span></a><nav className="hidden items-center gap-7 text-sm text-muted-foreground md:flex"><a href="#percurso">Percurso</a><a href="#laboratorios">Laboratórios</a><a href="#midiateca">Midiateca</a><a href="#professor">Professor</a></nav><Button onClick={()=>setMenu(!menu)} variant="outline" className="md:hidden" aria-label="Abrir menu">{menu?<X/>:<Menu/>}</Button><span className="hidden rounded-full border px-3 py-1 font-mono text-xs text-primary md:block">ENSINO MÉDIO • BNCC</span></div>{menu&&<nav className="mt-3 grid gap-2 border-t pt-3 md:hidden"><a href="#percurso">Percurso</a><a href="#laboratorios">Laboratórios</a><a href="#midiateca">Midiateca</a></nav>}</header>
 <section id="inicio" className="mx-auto grid min-h-[720px] max-w-[1500px] gap-6 px-5 py-8 lg:grid-cols-[280px_minmax(0,1fr)_310px] lg:px-10"><aside className="hidden rounded-2xl border bg-card/80 p-5 lg:block"><p className="font-mono text-xs text-primary">PAINEL DE MISSÃO</p><h2 className="mt-3 text-2xl font-bold">Seu percurso</h2><div className="mt-6 space-y-3">{['Observar o fenômeno','Definir grandezas','Coletar evidências','Construir o modelo','Defender a conclusão'].map((x,i)=><div key={x} className="flex gap-3"><span className={`grid size-7 shrink-0 place-items-center rounded-full border font-mono text-xs ${i===0?'border-primary bg-primary text-slate-950':''}`}>{i+1}</span><span className={i?'text-muted-foreground':''}>{x}</span></div>)}</div><div className="mt-8 rounded-xl bg-muted p-4"><CircleGauge className="text-sky-300"/><p className="mt-3 text-sm font-bold">Caderno de campo</p><p className="mt-1 text-xs text-muted-foreground">Previsão, medida, incerteza e revisão do modelo.</p></div></aside>
 <div className="instrument rounded-3xl border p-5 shadow-2xl shadow-sky-950/40 sm:p-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-mono text-xs text-sky-300">MISSÃO 01 • MECÂNICA</p><h1 className="mt-2 max-w-3xl text-4xl font-black tracking-tight sm:text-6xl">Faça o invisível virar <span className="text-primary">medida.</span></h1></div><Activity className="size-12 text-primary"/></div><p className="mt-5 max-w-2xl text-lg text-muted-foreground">A Física começa quando uma curiosidade ganha grandezas, instrumentos, dados e um modelo que pode falhar.</p><div className="axis relative mt-8 min-h-[300px] overflow-hidden rounded-2xl border bg-[#071426] p-5"><div className="flex items-center justify-between font-mono text-xs text-sky-200"><span>BANCADA • 2ª LEI DE NEWTON</span><span>ΣF = m·a</span></div><div className="mt-12 flex items-center"><div className="relative h-1 flex-1 bg-sky-400/40"><div className="absolute -top-8 left-[18%] grid h-16 w-24 place-items-center rounded-lg border-2 border-primary bg-[#142942] font-mono font-bold">{mass} kg</div><div className="absolute -top-1 left-[36%] h-1 bg-primary" style={{width:`${Math.min(force*1.5,50)}%`}}/><ChevronRight className="absolute -right-3 -top-3 text-primary"/></div></div><div className="mt-20 grid gap-4 sm:grid-cols-2"><label className="font-mono text-xs">FORÇA <b className="float-right text-primary">{force} N</b><input aria-label="Força resultante" type="range" min="0" max="60" value={force} onChange={e=>setForce(+e.target.value)} className="mt-3 w-full accent-yellow-400"/></label><label className="font-mono text-xs">MASSA <b className="float-right text-sky-300">{mass} kg</b><input aria-label="Massa" type="range" min="1" max="15" value={mass} onChange={e=>setMass(+e.target.value)} className="mt-3 w-full accent-sky-400"/></label></div></div><div className="mt-5 flex flex-wrap items-center justify-between gap-4"><div><span className="font-mono text-xs text-muted-foreground">ACELERAÇÃO PREVISTA</span><p className="font-mono text-3xl font-bold text-primary">{a.toFixed(2)} m/s²</p></div><Button className="h-11 bg-primary px-5 font-bold text-slate-950 hover:bg-yellow-300">Abrir investigação <ArrowRight/></Button></div></div>
 <aside className="space-y-5"><div className="rounded-2xl border bg-card p-5"><p className="font-mono text-xs text-primary">PERGUNTA-GUIA</p><h2 className="mt-3 text-xl font-bold">Dobrar a força sempre dobra a aceleração?</h2><p className="mt-3 text-sm text-muted-foreground">Faça uma previsão, mantenha a massa constante e produza dados.</p></div><div className="rounded-2xl border bg-sky-950/50 p-5"><Gauge className="text-sky-300"/><p className="mt-4 font-bold">Evidência esperada</p><p className="mt-2 text-sm text-muted-foreground">Tabela F × a, gráfico, ajuste proporcional e resolução do instrumento.</p><span className="mt-4 inline-flex items-center gap-2 text-xs text-emerald-300"><CheckCircle2 className="size-4"/> EM13CNT101 • 205</span></div></aside></section>
 <section id="percurso" className="border-y bg-[#081629] px-5 py-24 lg:px-10"><div className="mx-auto max-w-[1400px]"><p className="font-mono text-xs text-primary">ARQUITETURA CURRICULAR</p><div className="mt-3 grid gap-5 lg:grid-cols-[1fr_1.2fr]"><h2 className="text-4xl font-black sm:text-6xl">12 missões.<br/>Uma forma de pensar.</h2><p className="max-w-xl text-muted-foreground">A BNCC organiza competências da área, não capítulos. Esta progressão começa com medidas e modelos, avança por ondas e campos e termina nas fronteiras da Física.</p></div><div className="mt-10 flex flex-wrap gap-2">{years.map((y,i)=><button key={y.year} onClick={()=>setYear(i)} className={`rounded-full border px-5 py-3 font-bold ${year===i?'border-primary bg-primary text-slate-950':'bg-card'}`}>{y.year}</button>)}</div><article className="mt-5 grid gap-8 rounded-3xl border bg-card p-6 lg:grid-cols-[.8fr_1.2fr]"><div><p className="font-mono text-sm text-sky-300">{years[year].focus}</p><h3 className="mt-3 text-4xl font-black">{years[year].title}</h3><span className="mt-5 inline-block rounded-full bg-muted px-3 py-2 font-mono text-xs">{years[year].bncc}</span></div><ol className="grid gap-3 sm:grid-cols-2">{years[year].missions.map((m,i)=><li key={m} className="flex items-start gap-3 rounded-xl border bg-[#0a1728] p-4"><span className="font-mono text-primary">0{i+1}</span><b>{m}</b></li>)}</ol></article></div></section>
 <section id="laboratorios" className="px-5 py-24 lg:px-10"><div className="mx-auto max-w-[1400px]"><p className="font-mono text-xs text-primary">LABORATÓRIOS</p><h2 className="mt-3 max-w-3xl text-4xl font-black sm:text-6xl">Não siga receitas.<br/>Construa evidências.</h2><div className="mt-10 grid gap-4 md:grid-cols-2">{labs.map(({icon:Icon,...lab},i)=><article key={lab.title} className="group rounded-2xl border bg-card p-6 transition hover:-translate-y-1 hover:border-sky-400"><div className="flex items-start justify-between"><Icon className="size-9 text-primary"/><span className="font-mono text-xs text-muted-foreground">LAB {String(i+1).padStart(2,'0')} • {lab.risk}</span></div><h3 className="mt-8 text-2xl font-bold">{lab.title}</h3><p className="mt-3 text-sky-200">{lab.question}</p><dl className="mt-5 grid gap-3 text-sm"><div><dt className="font-mono text-xs text-muted-foreground">MÉTODO</dt><dd>{lab.method}</dd></div><div><dt className="font-mono text-xs text-muted-foreground">PRODUTO</dt><dd>{lab.evidence}</dd></div></dl></article>)}</div><div className="mt-6 grid gap-3 rounded-2xl border border-amber-300/30 bg-amber-300/5 p-5 md:grid-cols-4">{['Pergunta investigável','Variáveis e controles','Medição e incerteza','Argumento baseado em dados'].map((x,i)=><div key={x}><span className="font-mono text-primary">0{i+1}</span><p className="mt-1 font-bold">{x}</p></div>)}</div></div></section>
 <section id="midiateca" className="bg-[#eef3f8] px-5 py-24 text-slate-950 lg:px-10"><div className="mx-auto max-w-[1400px]"><div className="grid gap-5 lg:grid-cols-2"><div><p className="font-mono text-xs font-bold text-blue-700">MIDIATECA VERIFICADA</p><h2 className="mt-3 text-4xl font-black sm:text-6xl">Fontes oficiais,<br/>perguntas melhores.</h2></div><p className="max-w-xl text-slate-600">Prever antes, observar com propósito e explicar depois. Os links apontam para as instituições responsáveis.</p></div><div className="mt-10 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{media.map(item=><a key={item.title} href={item.href} target="_blank" rel="noreferrer" className="group flex min-h-52 flex-col rounded-2xl border border-slate-300 bg-white p-5 transition hover:-translate-y-1 hover:border-blue-600"><span className="font-mono text-xs font-bold text-blue-700">{item.org}</span><h3 className="mt-5 text-xl font-bold">{item.title}</h3><p className="mt-2 text-sm text-slate-500">{item.kind}</p><span className="mt-auto flex items-center gap-2 pt-5 text-sm font-bold">Abrir fonte oficial <ExternalLink className="size-4"/></span></a>)}</div><p className="mt-6 text-sm text-slate-600">Sugestão: use trechos com uma questão de observação e uma produção posterior; evite exibição sem mediação.</p></div></section>
 <section id="professor" className="px-5 py-24 lg:px-10"><div className="mx-auto grid max-w-[1400px] gap-8 lg:grid-cols-[1fr_1.2fr]"><div><BookOpen className="size-10 text-primary"/><h2 className="mt-5 text-4xl font-black">Para o professor</h2><p className="mt-4 max-w-lg text-muted-foreground">Planejamento reverso: comece pela evidência que o estudante produzirá. Depois escolha fenômeno, investigação e formalização.</p></div><div className="grid gap-3 sm:grid-cols-2">{['Plano de aula em 5E','Rubrica de argumentação','Protocolo de segurança','Caderno de dados','Diagnóstico conceitual','Projeto territorial'].map((x,i)=><div key={x} className="flex items-center gap-3 rounded-xl border bg-card p-4"><span className="grid size-9 place-items-center rounded-lg bg-muted font-mono text-primary">{i+1}</span><b>{x}</b></div>)}</div></div></section>
 <footer className="border-t px-5 py-8 text-sm text-muted-foreground lg:px-10"><div className="mx-auto flex max-w-[1400px] flex-wrap justify-between gap-3"><p><b className="text-white">Einstein — Física em Movimento</b> • projeto educacional aberto.</p><p>Experimentos reais exigem supervisão e análise de risco.</p></div></footer></main>}
